"""ice aktarma isleri tablosu

Revision ID: 3c855efb8a04
Revises: 03745900fb3f
Create Date: 2026-09-30 09:10:25.661270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.database


# revision identifiers, used by Alembic.
revision: str = '3c855efb8a04'
down_revision: Union[str, Sequence[str], None] = '03745900fb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('letterboxd', 'goodreads')", name=op.f('ck_import_jobs_source_valid')),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'failed')", name=op.f('ck_import_jobs_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_import_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_user_id'))

    op.drop_table('import_jobs')
    # ### end Alembic commands ###
