"""v2 ilk sema

Revision ID: fa1eb17da6a0
Revises: 
Create Date: 2026-09-26 14:35:18.714870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1eb17da6a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('backdrop_url', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('people', sa.JSON(), nullable=False),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('seasons', sa.Integer(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('external_rating', sa.Double(), nullable=True),
    sa.Column('external_votes', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('tmdb', 'openlibrary', 'google_books')", name=op.f('ck_contents_source_valid')),
    sa.CheckConstraint("type IN ('movie', 'tv', 'book')", name=op.f('ck_contents_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contents')),
    sa.UniqueConstraint('source', 'external_id', name='uq_contents_source_external')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_year'), ['year'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('favorite_genres', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('follower_id <> followed_id', name=op.f('ck_follows_not_self')),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name=op.f('fk_follows_followed_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_follows_follower_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name=op.f('pk_follows'))
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follows_followed_id'), ['followed_id'], unique=False)

    op.create_table('library_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('completed', 'in_progress', 'planned', 'dropped')", name=op.f('ck_library_entries_status_valid')),
    sa.CheckConstraint('rating BETWEEN 1 AND 10', name=op.f('ck_library_entries_rating_range')),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('fk_library_entries_content_id_contents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_library_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_entries')),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_library_entries_user_content')
    )
    with op.batch_alter_table('library_entries', schema=None) as batch_op:
        batch_op.create_index('ix_library_entries_content_rating', ['content_id', 'rating'], unique=False)
        batch_op.create_index('ix_library_entries_user_status', ['user_id', 'status'], unique=False)

    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_codes'))
    )
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_codes_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('has_spoiler', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('fk_reviews_content_id_contents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_reviews_user_content')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_content_created', ['content_id', 'created_at'], unique=False)

    op.create_table('user_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_lists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_lists'))
    )
    with op.batch_alter_table('user_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_lists_user_id'), ['user_id'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('verb', sa.String(length=20), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verb IN ('log', 'status', 'list_add', 'list_create')", name=op.f('ck_activities_verb_valid')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_activities_actor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('fk_activities_content_id_contents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['user_lists.id'], name=op.f('fk_activities_list_id_user_lists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_actor_id', ['actor_id', 'id'], unique=False)
        batch_op.create_index('ix_activities_content_id', ['content_id'], unique=False)

    op.create_table('list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('fk_list_items_content_id_contents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['user_lists.id'], name=op.f('fk_list_items_list_id_user_lists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'content_id', name=op.f('pk_list_items'))
    )
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.create_index('ix_list_items_list_position', ['list_id', 'position'], unique=False)

    op.create_table('activity_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_comments_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_comments'))
    )
    with op.batch_alter_table('activity_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_comments_activity_id'), ['activity_id'], unique=False)

    op.create_table('activity_likes',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_likes_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'user_id', name=op.f('pk_activity_likes'))
    )
    with op.batch_alter_table('activity_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_likes_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('follow', 'like', 'comment')", name=op.f('ck_notifications_type_valid')),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_notifications_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_notifications_actor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['activity_comments.id'], name=op.f('fk_notifications_comment_id_activity_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_recipient_unread', ['recipient_id', 'is_read', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_recipient_unread')

    op.drop_table('notifications')
    with op.batch_alter_table('activity_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_likes_user_id'))

    op.drop_table('activity_likes')
    with op.batch_alter_table('activity_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_comments_activity_id'))

    op.drop_table('activity_comments')
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.drop_index('ix_list_items_list_position')

    op.drop_table('list_items')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_content_id')
        batch_op.drop_index('ix_activities_actor_id')

    op.drop_table('activities')
    with op.batch_alter_table('user_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_lists_user_id'))

    op.drop_table('user_lists')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_content_created')

    op.drop_table('reviews')
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_user_id'))

    op.drop_table('password_reset_codes')
    with op.batch_alter_table('library_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_library_entries_user_status')
        batch_op.drop_index('ix_library_entries_content_rating')

    op.drop_table('library_entries')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_followed_id'))

    op.drop_table('follows')
    op.drop_table('users')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_year'))
        batch_op.drop_index(batch_op.f('ix_contents_type'))
        batch_op.drop_index(batch_op.f('ix_contents_title'))

    op.drop_table('contents')
    # ### end Alembic commands ###
